FROM php:8-apache
#atualizando os pacotes e instalando uzip e utilizatrios
RUN apt-get update && apt-get install -y --no-install-recommends \
  zip \
  bzip2 \
  unzip \
  apt-utils \
  libzip-dev

RUN docker-php-ext-install pdo_mysql mysqli zip
# Instalando o Composer
RUN php -r "copy('http://getcomposer.org/installer', 'composer-setup.php');"
RUN php composer-setup.php
RUN php -r "unlink('composer-setup.php');"
# RUN mv composer.phar /var/www/html

#PERMISSÕES DOS ARQUIVOS DO CD FONTE FUNCIONEM NO WINDOWS

RUN chown -R root:www-data /var/www/html
RUN chmod -R u+rwx,g+rx,o+rw /var/www/html
RUN find /var/www/html -type d -exec chmod u+rwx,g+rx,o+rx {} +
RUN find /var/www/html -type f -exec chmod u+rw,g+rw,o+r {} +



EXPOSE 80
EXPOSE 443
EXPOSE 3306
