version: '3.8'

services:
  app:
    build: ./php
    container_name: "MAGAZORD-WEB"
    volumes:
      - ../:/var/www/html
    ports:
      - 80:80
      - 443:443

    networks:
      - magazord-rede
    restart: always

    environment:
      - APACHE_DOCUMENTROOT=/var/www/html
      - APACHE_MOD_REWRITE=On
      - PHP_ERROR_LOG=/var/www/html/logs/error.log
      - PHP_LOG_DIR=/var/www/html/logs
      - PHP_LOG_LEVEL=debug
      
    depends_on:
      - mysql
    links:
      - mysql

  mysql:
    image: mysql
    restart: always
    ports:
      - 3306:3306
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - magazord-rede
    container_name: "MAGAZORD-BD"
    environment:
      MYSQL_ROOT_PASSWORD: root


networks:
  magazord-rede:
    driver: bridge
